### ISSUE TITLE
API Key

### ISSUE THREAD

**Issue by Aevyz** [emmanuelstroem/tampered_checker#1]
Heyho, you might not want to have your api key uploaded for the whole world to see:

https://github.com/emmanuelstroem/tampered_checker/blob/6b09e76710c80c0bce682c0a53f10cd82f1aff84/app/src/main/java/in/manu/checker/AndroidDeviceVerifier.java#L44

**Comment by emmanuelstroem** [comment]
thanks @Aevyz.
however, the project with that key was deleted a long time ago.
but removed it anyways. 😄
